theme: jekyll-theme-minimal
title: Web & Video Conferencing Apps as Distruptive Technologies
description: The pandemic has changed how different businesses operate, especially working spaces, flight services and lodging, and other industries. Web-conferencing software has disrupted multiple businesses in this area, and has helped people work and communicate remotely.
menu bar: Article 1
